workflows:
  liferoute-ios:
    name: LifeRoute iOS
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Brandon

    environment:
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: Com.Brandongood.LifeRoute

    scripts:
      - name: Show Xcode version
        script: |
          xcodebuild -version

      - name: Apply signing profiles
        script: |
          xcode-project use-profiles

      - name: Build LifeRoute IPA
        script: |
          xcode-project build-ipa \
            --project "LifeRoute.xcodeproj" \
            --scheme "LifeRoute" \
            --clean \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
