#ifndef LIVING_ATMOSPHERE_MOTION_H
#define LIVING_ATMOSPHERE_MOTION_H

// Common air-system engineering rates; frozen with the first participating scene.
#define LIVING_AIR_METEOR_START_RANGE 38.0f
#define LIVING_AIR_WARP_X 0.023f
#define LIVING_AIR_WARP_Y 0.019f
#define LIVING_AIR_FINE_DRIFT 0.014f
#define LIVING_AIR_FINE_REFORM 0.027f
#define LIVING_AIR_CLOUD_ADVECTION 0.053f
#define LIVING_AIR_CLOUD_VERTICAL 0.009f
#define LIVING_AIR_FOG_FAR 0.035f
#define LIVING_AIR_FOG_NEAR 0.059f
#define LIVING_AIR_STAR_RATE 0.63f
#define LIVING_AIR_METEOR_SEED_SCALE 0.73f
#define LIVING_AIR_METEOR_SLOT 71.0f
#define LIVING_AIR_METEOR_START_MIN 14.0f
#define LIVING_AIR_METEOR_DURATION 0.75f
#define LIVING_AIR_METEOR_TRAVEL_RATE 0.23f
#define LIVING_AIR_SNOW_DRIFT_BASE 0.5f
#define LIVING_AIR_SNOW_DRIFT_DEPTH 0.30f
#define LIVING_AIR_SNOW_FALL_BASE 0.8f
#define LIVING_AIR_SNOW_FALL_DEPTH 0.8f
#define LIVING_AIR_RAIN_DRIFT 0.8f
#define LIVING_AIR_RAIN_FALL_BASE 6.0f
#define LIVING_AIR_RAIN_FALL_DEPTH 4.0f
#define LIVING_AIR_SNOW_SWAY_BASE 0.7f
#define LIVING_AIR_SNOW_SWAY_DEPTH 0.2f
#endif
