#ifndef LIVING_OCEAN_TIMING_H
#define LIVING_OCEAN_TIMING_H

// Canonical Ocean timing authority. Extracted without retuning from 15b4266.
// Metal includes this file; the Swift GPU tests import this same C header.
// FROZEN after the authority-establishment commit: changing any value requires
// owner authorization outside the current Living Themes expansion.
#define LIVING_OCEAN_ARRIVAL_SPACING 6.3f
#define LIVING_OCEAN_START_JITTER 1.7f
#define LIVING_OCEAN_LIFETIME_MIN 14.2f
#define LIVING_OCEAN_LIFETIME_VARIATION 3.8f
#define LIVING_OCEAN_LIFETIME_MAX 18.0f
#define LIVING_OCEAN_START_SEED 19.73f
#define LIVING_OCEAN_LIFETIME_SEED 71.1f
#define LIVING_OCEAN_EVENT_SLOTS 5
#define LIVING_OCEAN_ENVELOPE_START 0.0f
#define LIVING_OCEAN_ENVELOPE_FULL 0.09f
#define LIVING_OCEAN_DISSIPATION_START 0.82f
#define LIVING_OCEAN_DISSIPATION_END 1.0f
#define LIVING_OCEAN_SWELL_START 0.0f
#define LIVING_OCEAN_SWELL_FULL 0.18f
#define LIVING_OCEAN_SWELL_DECAY 0.58f
#define LIVING_OCEAN_SWELL_END 0.78f
#define LIVING_OCEAN_CREST_START 0.19f
#define LIVING_OCEAN_CREST_FULL 0.40f
#define LIVING_OCEAN_CREST_DECAY 0.54f
#define LIVING_OCEAN_CREST_END 0.72f
#define LIVING_OCEAN_BREAK_START 0.37f
#define LIVING_OCEAN_BREAK_FULL 0.53f
#define LIVING_OCEAN_BREAK_DECAY 0.65f
#define LIVING_OCEAN_BREAK_END 0.83f
#define LIVING_OCEAN_FOAM_START 0.47f
#define LIVING_OCEAN_FOAM_FULL 0.66f
#define LIVING_OCEAN_FOAM_DECAY 0.79f
#define LIVING_OCEAN_FOAM_END 1.0f
#define LIVING_OCEAN_TRAVEL_EXPONENT 1.36f
#define LIVING_OCEAN_CALM_TIME_SCALE 0.42f
#define LIVING_OCEAN_FULL_TIME_SCALE 1.0f
#define LIVING_OCEAN_CURL_RATE 0.48f
#define LIVING_OCEAN_WAKE_SPREAD_START 0.48f
#define LIVING_OCEAN_WAKE_SPREAD_END 0.92f
#define LIVING_OCEAN_FOAM_ADVECTION_RATE 1.9f
#define LIVING_OCEAN_FOAM_CROSS_RATE 0.27f
#define LIVING_OCEAN_RIPPLE_RATE 2.7f
#define LIVING_OCEAN_RIPPLE_EVOLUTION_RATE 0.08f
#define LIVING_OCEAN_SPRAY_CROSS_RATE 1.0f
#define LIVING_OCEAN_SPRAY_RISE_RATE 2.7f
// Required meaningful overlap sample: later swell is developed, not a zero tail.
#define LIVING_OCEAN_OVERLAP_SWELL_PROGRESS 0.20f
#endif
